In [1]:
import pandas as pd

In [19]:
activity = pd.read_csv("./with_chewing_data.csv")

In [20]:
no_activity = pd.read_csv("./without_chewing_data.csv")

In [21]:
len(activity), len(no_activity)

(895, 893)

In [22]:
no_activity["target"] = 0
activity["target"] = 1

In [23]:
no_activity = no_activity[:780]

In [24]:
activity = activity[:780]

In [18]:
780/60

13.0

In [15]:
3120/ 60

52.0

In [25]:
no_activity = no_activity.to_numpy().reshape(-1, 3 * 20) #reshape(-1, 10, 3)

In [26]:
activity = activity.to_numpy().reshape(-1, 3 * 20)

# Cluster

In [27]:
import numpy as np

In [28]:
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [31]:
model = KMeans(n_clusters=2)

In [32]:
X = np.concatenate([no_activity, activity])
Y = np.concatenate([[0] * len(no_activity), [1] * len(activity)])

In [33]:
model.fit(X)

c:\Users\Tarif\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=2)

In [34]:
model.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Decision Tree

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X, Y = shuffle(X, Y)

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=12)

In [39]:
dtree_clf = DecisionTreeClassifier()

In [41]:
dtree_clf.fit(X_train, Y_train)

DecisionTreeClassifier()

In [42]:
accuracy_score(Y_test, dtree_clf.predict(X_test))

1.0

# Export

In [43]:
import pickle as pkl

In [45]:
import joblib

In [30]:
pkl.dump(dtree_clf, open("model_weights.pkl", "wb"))

In [46]:
joblib.dump(dtree_clf, "model_weights_jlib_2.pkl", compress=9)

['model_weights_jlib_2.pkl']

# Load Back

In [47]:
new_model = pkl.load(open("./model_weights.pkl", "rb"))

FileNotFoundError: [Errno 2] No such file or directory: './model_weights.pkl'

In [4]:
sample_data = [[-9.38,  4.39,  0.12, -9.34,  4.39,  0.2 , -9.45,  4.35,  0.12,
        -9.38,  4.47,  0.16, -9.38,  4.43,  0.2 , -9.38,  4.39,  0.2 ,
        -9.34,  4.43,  0.2 , -9.34,  4.43,  0.16, -9.34,  4.39,  0.24,
        -9.41,  4.39,  0.12]]

In [5]:
new_model.predict(sample_data)

array([0])